name: composite-action-shell
description: 'composite action shell'

runs:
  using: "composite"
  steps:
  

    - name: exec script
      run: chmod +x bash_test.sh
      shell: bash

    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

   - name: run script
     run: bash_test.sh
     shell: bash

 

