name: composite-action-shell
description: 'composite action shell'

runs:
  using: "composite"
  steps:
  

    - name: exec script
      run: chmod +x bash_test
      shell: bash

    - name: run script
      run: bash_test
      shell: bash

 

