name: composite-action-shell
description: 'composite action shell'

inputs:
  software:  
    description: 'File to install package from'
    required: true
    default: 'kubeclt'
  version:
    description: 'version to install'
    required: true
    default: '1.0'

runs:
  using: "composite"
  env:
    var: "test variable"
  steps:
  

    - name: exec script
      run: chmod +x bash_test.sh
      shell: bash

    - name: run script
      run: ./bash_test.sh ${{env.var}}
      shell: bash

 

