name: composite-action-shell
description: 'composite action shell'

inputs:
 variable:  
    description: 'File to install package from'
    required: true
    default: '1st Variable'

runs:
  using: "composite"
  steps:
  

    - name: exec script
      run: chmod +x bash_test.sh
      shell: bash

    - name: run script
      run: ./bash_test.sh ${{inputs.variable}}
      shell: bash

 

