name: composite-action-shell
description: 'composite action shell'

runs:
  using: "composite"
  steps:
  

    - name: exec script
      run: chmod +x bash_test.sh
      shell: bash

    - name: run script
      run: cat bash_test.sh
      shell: bash

 

