name: test

on: push


jobs:
    first:
        
        runs-on: ubuntu-latest
        
        steps:
        - name: checkout 
          uses: actions/checkout@v4

        - name: ls
          run: cat README.md
    
    second:
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: ls
        run: cat file.txt



      
        
