name: test
on: [push, workflow_dispatch]
jobs:
    first:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: ls
          run: "ls -l"
