name: test

on: push
env:
  info: yes


jobs:
    first:
        
        runs-on: ubuntu-latest
        
        steps:
        - name: checkout 
          uses: actions/checkout@v4

        - name: ls
          run: |
               cat README.md
               echo -e "\n"
               echo ${{env.info}}

        - name: produce_output
          id: ids
          run: echo "value=TEST" >> $GITHUB_OUTPUT

        - name: collect_output
          run: echo "The ouput is ${{steps.ids.outputs.valulle}}"
    
    second:
      if: always()
      runs-on: ubuntu-latest
  
      needs: first
      steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: ls
        run: cat file.txt



      
        
