name: test

on: push
env:
  info: yes


jobs:
    first:
        
        runs-on: ubuntu-latest
        
        steps:
        - name: checkout 
          uses: actions/checkout@v4

        - name: ls
          run: |
               cat README.md
               echo -e "\n"
               echo $info
    
    second:
      runs-on: ubuntu-latest
      needs: first
      steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: ls
        run: cat file.txt



      
        
