name: test

on: 
  - push
  - workflow_dispatch
  - pull_request
env:
  info: yes


jobs:
    first:
     
      outputs:
        output1: ${{steps.ids.outputs.value}}  
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v4
   

  
      - name: produce_output
        id: ids
        run: | 
          echo "value=TEST_VALEUR" >> $GITHUB_OUTPUT
          echo "var=JDKD" >> $GITHUB_ENV
          echo "var1=1JDKD" >> $GITHUB_ENV
        
          
          

      - name: collect_output
       
        run: |
          echo "The ouput is ${{steps.ids.outputs.value}}"
          echo "values from previous step are $var $var1"
      
  
      - name: setup
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10' 
          cache: pip
    
          
      - name: install packages
        run: pip install -r requirements.txt


      - name: run_script
        run : python file.py
        

        
    second:
      
      runs-on: ubuntu-latest
  
      needs: first
      steps:
      - name: display
        run: echo ${{needs.first.outputs.output1}} 
        

      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: zoundibona/git_test
          token: ${{secrets.token}}    
        
      
      - name: list dir
        run: |

             
             sed -i s/line/changeline/g file.txt
             git config --global user.email "zoundibona@yahoo.fr"
             git config --global user.name "zoundibona"
             git add file.txt
             git commit -m updatefile
             git push
    
    third:
      #if: github.ref=='refs/heads/dev'
      runs-on: ubuntu-latest
      environment: dev
      needs: second
      steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: display
          run: ls -l

    fourth:
        if: github.event_name=='pull_request'
        runs-on: ubuntu-latest
        
        needs: second
        steps:
            - name: checkout
              uses: actions/checkout@v4
      
            - name: display
              run: ls -a
      


   


      
        

