name: test

on: 
  workflow_dispatch:
  push:
  pull_request:
   types: synchronize
env:
  soft: "kubectl"
  version: "1.0"


jobs:
    first:
     
      outputs:
        output1: ${{steps.ids.outputs.value}}  
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v4
   

  
      - name: produce_output
        id: ids
        run: | 
          echo "value=TEST_VALEUR" >> $GITHUB_OUTPUT
          echo "var1=1JDKD" >> $GITHUB_ENV
        
      
      - name: collect_output
       
        run: |
          echo "The ouput is ${{steps.ids.outputs.value}}"
          
      
  
      - name: setup
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10' 
          cache: pip
    
          
      - name: install packages
        uses: ./.github/actions
        with:
          filename: requirements.txt
      
      - name: shell_output
        uses: ./.github/actions_shell
        with:
          software: ${{env.soft}}
          version: ${{env.version}}
     #   run: pip install -r requirements.txt


      - name: run_script
        run : python file.py
        

        
    second:
      
      runs-on: ubuntu-latest
  
      needs: first
      steps:
      - name: display
        run: echo ${{needs.first.outputs.output1}} 
        

      - name: checkout
        uses: actions/checkout@v4
        with:
          repository: zoundibona/git_test
          token: ${{secrets.token}}    
        
      
      - name: list dir
        run: |

             
             sed -i s/line/changeline/g file.txt
             git config --global user.email "zoundibona@yahoo.fr"
             git config --global user.name "zoundibona"
             git add file.txt
             git commit -m updatefile
             git push
    
    dev:
      
      if: github.ref=='refs/heads/dev'
      runs-on: ubuntu-latest
     # environment: dev
      
      needs: second
      steps:
          - name: checkout
            uses: actions/checkout@v4
    
          - name: display
            run: ls -a
    
      
    prod:
        if: github.ref=='refs/heads/main'
        runs-on: ubuntu-latest
      #  environment: prod
        
        needs: second
        steps:
            - name: checkout
              uses: actions/checkout@v4
      
            - name: display
              run: ls -a
      


   


      
        

